### ISSUE TITLE
[Bug?]: Removing a hotspot from map does not remove it from Itinerary

### ISSUE THREAD

**Issue by j-applese3d** [rawcomposition/bird-planner#12]
Steps to reproduce:
1. add a hotspot to a trip
2. add it to the itinerary
3. remove it from Hotspots Map (3 dots -> Remove from trip)
4. Note that Itinerary now has an "Unknown Location"
5. (if you add the location back, then Itinerary does update to show the location name again, **so maybe this is a feature?**)

-----

I suggest that if you remove a hotspot, it should be removed from the itinerary too.
Optionally there could be a confirmation dialog:
> **Are you sure?** By removing &lt;location name&gt; your itinerary will be adjusted to remove this stop.

Another option would be to leave it like it is now, but show "Removed: location_name" in the itinerary - having it still link to the hotspot so that it can be added back easily from the Itinerary page...

It's not a big deal as it is either :)

**Comment by j-applese3d** [comment]
One thing that may would probably be required (if removing the location) is that the driving time(s) would need to be recalculated.

Based on this, and the below issues, I think the better option might be to just "keep" the hotspot, but mark it as removed -- hiding it from the map, and adjusting the description in the itinerary. Then the user can remove the stop from their itinerary manually (if it has a red background or :warning: icon or similar, it should be easy for them to see the problem)


At the moment, if you *move* the "Unknown Location" it will give you errors about not being able to calculate distances (I presume because it no longer has the coordinates to pass to mapbox?)

![image](https://github.com/rawcomposition/bird-planner/assets/24463871/03279c0c-77d4-4a71-a4d7-b4c5680deb54)


The other thing is if you click the Unknown Location you receive a JS error.
![image](https://github.com/rawcomposition/bird-planner/assets/24463871/d62df99e-f1af-4a19-95a1-873b63165d33)

**Comment by rawcomposition** [comment]
Excellent observations and summary! I'll work on a solution for it (likely the latter one you suggested).

**Comment by rawcomposition** [comment]
I just merged in the changes outlined here: https://github.com/rawcomposition/bird-planner/pull/13

Let me know if you think any of those changes should be tweaked at all. I left the error alert that pops up when calculating distance fails, I think that's still helpful. It will motivate them to delete the problematic location that no longer exists.
